Lethe Open-Source Library: MFNavierStokesPreconditionGMG< dim > Class Template Reference
MFNavierStokesPreconditionGMG< dim > Class Template Reference
#include <mf_navier_stokes.h>
Public Member Functions
void initialize_ls (TimerOutput &computing_timer, const DoFHandler< dim > &dof_handler, const SimulationParameters< dim > &simulation_parameters, const std::shared_ptr< Mapping< dim >> &mapping, const std::shared_ptr< FESystem< dim >> fe, TimerOutput &mg_computing_timer, const std::shared_ptr< Quadrature< dim >> &cell_quadrature, const std::shared_ptr< Function< dim >> forcing_function, const VectorType &present_solution, const VectorType &time_derivative_previous_solutions, const ConditionalOStream &pcout, const std::shared_ptr< SimulationControl > simulation_control, FlowControl< dim > &flow_control)
void initialize_gc (TimerOutput &computing_timer, const DoFHandler< dim > &dof_handler, const SimulationParameters< dim > &simulation_parameters, const std::shared_ptr< Mapping< dim >> &mapping, const std::shared_ptr< FESystem< dim >> fe, TimerOutput &mg_computing_timer, const std::shared_ptr< Quadrature< dim >> &cell_quadrature, const std::shared_ptr< Function< dim >> forcing_function, const VectorType &present_solution, const VectorType &time_derivative_previous_solutions, const ConditionalOStream &pcout, const std::shared_ptr< SimulationControl > simulation_control, FlowControl< dim > &flow_control)
void vmult (VectorType &dst, const VectorType &src) const
Private Types
using VectorType = LinearAlgebra::distributed::Vector< double >
using LSTransferType = MGTransferMatrixFree< dim, double >
using GCTransferType = MGTransferGlobalCoarsening< dim, VectorType >
using OperatorType = NavierStokesOperatorBase< dim, double >
using SmootherPreconditionerType = DiagonalMatrix< VectorType >
using SmootherType = PreconditionRelaxation< OperatorType, SmootherPreconditionerType >
using PreconditionerTypeLS = PreconditionMG< dim, VectorType, LSTransferType >
using PreconditionerTypeGC = PreconditionMG< dim, VectorType, GCTransferType >
Private Attributes
MGLevelObject< DoFHandler< dim > > dof_handlers
MGLevelObject< MGTwoLevelTransfer< dim, VectorType > > transfers
MGLevelObject< std::shared_ptr< OperatorType > > mg_operators
std::shared_ptr< mg::Matrix< VectorType > > mg_matrix
std::shared_ptr< mg::Matrix< VectorType > > mg_interface_matrix_in
MGLevelObject< MatrixFreeOperators::MGInterfaceOperator< OperatorType > > ls_mg_operators
MGLevelObject< MatrixFreeOperators::MGInterfaceOperator< OperatorType > > ls_mg_interface_in
std::shared_ptr< MGSmootherPrecondition< OperatorType, SmootherType, VectorType > > mg_smoother
MGConstrainedDoFs mg_constrained_dofs
std::shared_ptr< LSTransferType > mg_transfer_ls
std::shared_ptr< GCTransferType > mg_transfer_gc
TrilinosWrappers::PreconditionAMG precondition_amg
TrilinosWrappers::PreconditionILU precondition_ilu
std::shared_ptr< ReductionControl > coarse_grid_solver_control
std::shared_ptr< SolverGMRES< VectorType > > coarse_grid_solver
std::shared_ptr< MGCoarseGridBase< VectorType > > mg_coarse
std::shared_ptr< Multigrid< VectorType > > mg
std::shared_ptr< PreconditionMG< dim, VectorType, LSTransferType > > ls_multigrid_preconditioner
std::shared_ptr< PreconditionMG< dim, VectorType, GCTransferType > > gc_multigrid_preconditioner
Detailed Description
template<int dim>
class MFNavierStokesPreconditionGMG< dim >
A geometric multigrid preconditioner compatible with the matrix-free solver.
Definition at line 44 of file mf_navier_stokes.h.
Member Typedef Documentation
GCTransferType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::GCTransferType = MGTransferGlobalCoarsening<dim, VectorType> private
Definition at line 48 of file mf_navier_stokes.h.
LSTransferType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::LSTransferType = MGTransferMatrixFree<dim, double> private
Definition at line 47 of file mf_navier_stokes.h.
OperatorType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::OperatorType = NavierStokesOperatorBase<dim, double> private
Definition at line 49 of file mf_navier_stokes.h.
PreconditionerTypeGC
template<int dim> using MFNavierStokesPreconditionGMG< dim >::PreconditionerTypeGC = PreconditionMG<dim, VectorType, GCTransferType> private
Definition at line 54 of file mf_navier_stokes.h.
PreconditionerTypeLS
template<int dim> using MFNavierStokesPreconditionGMG< dim >::PreconditionerTypeLS = PreconditionMG<dim, VectorType, LSTransferType> private
Definition at line 53 of file mf_navier_stokes.h.
SmootherPreconditionerType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::SmootherPreconditionerType = DiagonalMatrix<VectorType> private
Definition at line 50 of file mf_navier_stokes.h.
SmootherType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::SmootherType = PreconditionRelaxation<OperatorType, SmootherPreconditionerType> private
Definition at line 51 of file mf_navier_stokes.h.
VectorType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::VectorType = LinearAlgebra::distributed::Vector<double> private
Definition at line 46 of file mf_navier_stokes.h.
Member Function Documentation
initialize_gc()
template<int dim> void MFNavierStokesPreconditionGMG< dim >::initialize_gc (TimerOutput & computing_timer, const DoFHandler< dim > & dof_handler, const SimulationParameters< dim > & simulation_parameters, const std::shared_ptr< Mapping< dim >> & mapping, const std::shared_ptr< FESystem< dim >> fe, TimerOutput & mg_computing_timer, const std::shared_ptr< Quadrature< dim >> & cell_quadrature, const std::shared_ptr< Function< dim >> forcing_function, const VectorType & present_solution, const VectorType & time_derivative_previous_solutions, const ConditionalOStream & pcout, const std::shared_ptr< SimulationControl > simulation_control, FlowControl< dim > & flow_control)
Initialize all relevant objects needed for the local smoothing geometric multigrid approach.
Parameters
[in] computing_timer General solver timer.
[in] dof_handler Describes the layout of DoFs and the type of FE.
[in] simulation_parameters Object containing all parameters specified in input file.
[in] mapping Describes the transformations from unit to real cell.
[in] fe Describes the FE system for the vector-valued problem.
[in] mg_computing_timer Timer for specific MG components.
[in] cell_quadrature Required for local operations on cells.
[in] forcing_function Function specified in parameter file as source term.
[in] present_solution Previous solution needed to evaluate the non linear term.
[in] time_derivative_previous_solutions Vector storing time derivatives of previous solutions.
[in] pcout Object that allows parallel printing.
[in] simulation_control Required to get the time stepping method.
Definition at line 586 of file mf_navier_stokes.cc.
References fluid_dynamics, and SimulationParameters< dim >::linear_solver.
initialize_ls()
template<int dim> void MFNavierStokesPreconditionGMG< dim >::initialize_ls (TimerOutput & computing_timer, const DoFHandler< dim > & dof_handler, const SimulationParameters< dim > & simulation_parameters, const std::shared_ptr< Mapping< dim >> & mapping, const std::shared_ptr< FESystem< dim >> fe, TimerOutput & mg_computing_timer, const std::shared_ptr< Quadrature< dim >> & cell_quadrature, const std::shared_ptr< Function< dim >> forcing_function, const VectorType & present_solution, const VectorType & time_derivative_previous_solutions, const ConditionalOStream & pcout, const std::shared_ptr< SimulationControl > simulation_control, FlowControl< dim > & flow_control)
Initialize all relevant objects needed for the local smoothing geometric multigrid approach.
Parameters
[in] computing_timer General solver timer.
[in] dof_handler Describes the layout of DoFs and the type of FE.
[in] simulation_parameters Object containing all parameters specified in input file.
[in] mapping Describes the transformations from unit to real cell.
[in] fe Describes the FE system for the vector-valued problem.
[in] mg_computing_timer Timer for specific MG components.
[in] cell_quadrature Required for local operations on cells.
[in] forcing_function Function specified in parameter file as source term.
[in] present_solution Previous solution needed to evaluate the non linear term.
[in] time_derivative_previous_solutions Vector storing time derivatives of previous solutions.
[in] pcout Object that allows parallel printing.
[in] simulation_control Required to get the time stepping method.
Definition at line 50 of file mf_navier_stokes.cc.
References Parameters::LinearSolver::amg, SimulationParameters< dim >::boundary_conditions, Parameters::DynamicFlowControl::enable_flow_control, SimulationParameters< dim >::flow_control, fluid_dynamics, BoundaryConditions::function_weak, FlowControl< dim >::get_beta(), PhysicalPropertiesManager::get_kinematic_viscosity_scale(), Parameters::LinearSolver::ilu, is_bdf(), SimulationParameters< dim >::linear_solver, BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::periodic, SimulationParameters< dim >::physical_properties_manager, BoundaryConditions::pressure, pressure, Parameters::quiet, BoundaryConditions::slip, Parameters::Stabilization::stabilization, and SimulationParameters< dim >::stabilization.
vmult()
template<int dim> void MFNavierStokesPreconditionGMG< dim >::vmult (VectorType & dst, const VectorType & src) const
Calls the v cycle function of the multigrid object.
Parameters
[in,out] dst Destination vector holding the result.
[in] src Input source vector.
Definition at line 1115 of file mf_navier_stokes.cc.
Member Data Documentation
coarse_grid_solver
template<int dim> std::shared_ptr<SolverGMRES<VectorType> > MFNavierStokesPreconditionGMG< dim >::coarse_grid_solver private
GMRES as coarse grid solver.
Definition at line 183 of file mf_navier_stokes.h.
coarse_grid_solver_control
template<int dim> std::shared_ptr<ReductionControl> MFNavierStokesPreconditionGMG< dim >::coarse_grid_solver_control private
Solver control for the coarse grid solver.
Definition at line 180 of file mf_navier_stokes.h.
dof_handlers
template<int dim> MGLevelObject<DoFHandler<dim> > MFNavierStokesPreconditionGMG< dim >::dof_handlers private
DoF handlers for each of the levels of the global coarsening algorithm.
Definition at line 140 of file mf_navier_stokes.h.
gc_multigrid_preconditioner
template<int dim> std::shared_ptr<PreconditionMG<dim, VectorType, GCTransferType> > MFNavierStokesPreconditionGMG< dim >::gc_multigrid_preconditioner private
Global coarsening multigrid preconiditoner object.
Definition at line 197 of file mf_navier_stokes.h.
ls_mg_interface_in
template<int dim> MGLevelObject<MatrixFreeOperators::MGInterfaceOperator<OperatorType> > MFNavierStokesPreconditionGMG< dim >::ls_mg_interface_in private
Definition at line 156 of file mf_navier_stokes.h.
ls_mg_operators
template<int dim> MGLevelObject<MatrixFreeOperators::MGInterfaceOperator<OperatorType> > MFNavierStokesPreconditionGMG< dim >::ls_mg_operators private
Definition at line 154 of file mf_navier_stokes.h.
ls_multigrid_preconditioner
template<int dim> std::shared_ptr<PreconditionMG<dim, VectorType, LSTransferType> > MFNavierStokesPreconditionGMG< dim >::ls_multigrid_preconditioner private
Local smoothing multigrid preconditioner object.
Definition at line 193 of file mf_navier_stokes.h.
mg
template<int dim> std::shared_ptr<Multigrid<VectorType> > MFNavierStokesPreconditionGMG< dim >::mg private
Multigrid method.
Definition at line 189 of file mf_navier_stokes.h.
mg_coarse
template<int dim> std::shared_ptr<MGCoarseGridBase<VectorType> > MFNavierStokesPreconditionGMG< dim >::mg_coarse private
Multigrid wrapper for the coarse grid solver.
Definition at line 186 of file mf_navier_stokes.h.
mg_constrained_dofs
template<int dim> MGConstrainedDoFs MFNavierStokesPreconditionGMG< dim >::mg_constrained_dofs private
Collection of boundary constraints and refinement edge constrations for the different levels in the local smoothing approach.
Definition at line 165 of file mf_navier_stokes.h.
mg_interface_matrix_in
template<int dim> std::shared_ptr<mg::Matrix<VectorType> > MFNavierStokesPreconditionGMG< dim >::mg_interface_matrix_in private
Interface edge matrix needed only for local smoothing.
Definition at line 152 of file mf_navier_stokes.h.
mg_matrix
template<int dim> std::shared_ptr<mg::Matrix<VectorType> > MFNavierStokesPreconditionGMG< dim >::mg_matrix private
Multigrid level object storing all operators.
Definition at line 149 of file mf_navier_stokes.h.
mg_operators
template<int dim> MGLevelObject<std::shared_ptr<OperatorType> > MFNavierStokesPreconditionGMG< dim >::mg_operators private
Level operators for the geometric multigrid.
Definition at line 146 of file mf_navier_stokes.h.
mg_smoother
template<int dim> std::shared_ptr< MGSmootherPrecondition<OperatorType, SmootherType, VectorType> > MFNavierStokesPreconditionGMG< dim >::mg_smoother private
Smoother object.
Definition at line 161 of file mf_navier_stokes.h.
mg_transfer_gc
template<int dim> std::shared_ptr<GCTransferType> MFNavierStokesPreconditionGMG< dim >::mg_transfer_gc private
Transfer operator for global coarsening.
Definition at line 171 of file mf_navier_stokes.h.
mg_transfer_ls
template<int dim> std::shared_ptr<LSTransferType> MFNavierStokesPreconditionGMG< dim >::mg_transfer_ls private
Transfer operator for local smoothing.
Definition at line 168 of file mf_navier_stokes.h.
precondition_amg
template<int dim> TrilinosWrappers::PreconditionAMG MFNavierStokesPreconditionGMG< dim >::precondition_amg private
Algebraic multigrid as coarse grid solver.
Definition at line 174 of file mf_navier_stokes.h.
precondition_ilu
template<int dim> TrilinosWrappers::PreconditionILU MFNavierStokesPreconditionGMG< dim >::precondition_ilu private
Incomplete LU as coarse grid solver.
Definition at line 177 of file mf_navier_stokes.h.
transfers
template<int dim> MGLevelObject<MGTwoLevelTransfer<dim, VectorType> > MFNavierStokesPreconditionGMG< dim >::transfers private
Transfers for each of the levels of the global coarsening algorithm.
Definition at line 143 of file mf_navier_stokes.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/mf_navier_stokes.h
/home/runner/work/lethe/lethe/source/solvers/mf_navier_stokes.cc