Lethe Open-Source Library: /home/runner/work/lethe/lethe/include/core/grids.h File Reference
grids.h File Reference
#include <core/boundary_conditions.h>
#include <core/manifolds.h>
#include <core/parameters.h>
#include <deal.II/distributed/tria_base.h>
Functions
template<int dim, int spacedim = dim>
void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const Parameters::Mesh &mesh_parameters)
template<int dim, int spacedim = dim>
void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const BoundaryConditions::BoundaryConditions< spacedim > &boundary_conditions)
template<int dim, int spacedim = dim>
void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const Parameters::Mesh &mesh_parameters, const Parameters::Manifolds &manifolds_parameters, const bool &restart, const BoundaryConditions::BoundaryConditions< spacedim > &boundary_conditions)
template<int dim, int spacedim = dim>
void refine_triangulation_at_boundaries (const std::vector< int > boundary_ids, const unsigned int n_refinement, parallel::DistributedTriangulationBase< dim, spacedim > &triangulation)
Function Documentation
attach_grid_to_triangulation()
template<int dim, int spacedim = dim> void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const Parameters::Mesh & mesh_parameters)
Attaches a grid to a triangulation using mesh parameters.
Parameters
triangulation The triangulation to which a grid is attached
mesh_parameters The mesh parameters used to decide what type of mesh or primitive is used
boundary_conditions The information about the boundary conditions id. This is used to set-up the periodicity of the domain
Definition at line 21 of file grids.cc.
References Parameters::Mesh::colorized_cylinder_shell, Parameters::Mesh::cylinder, Parameters::Mesh::dealii, Parameters::Mesh::file_name, Parameters::Mesh::gmsh, Parameters::Mesh::grid_arguments, Parameters::Mesh::grid_type, Parameters::Mesh::initial_refinement, PeriodicHillsGrid< dim, spacedim >::make_grid(), Parameters::Mesh::periodic_hills, Parameters::Mesh::simplex, and Parameters::Mesh::type.
read_mesh_and_manifolds()
template<int dim, int spacedim = dim> void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const Parameters::Mesh & mesh_parameters, const Parameters::Manifolds & manifolds_parameters, const bool & restart, const BoundaryConditions::BoundaryConditions< spacedim > & boundary_conditions)
Completely set-up a mesh and its manifold.
Parameters
triangulation The triangulation to which a grid is attached
mesh_parameters The mesh parameters used to decide what type of mesh or primitive is used
manifolds_parameters The information about the type of manifolds attached to the boundary conditions
boundary_conditions The information about the boundary conditions id. This is used to set-up the periodicity of the domain
Definition at line 413 of file grids.cc.
References attach_grid_to_triangulation(), attach_manifolds_to_triangulation(), Parameters::Mesh::boundaries_to_refine, Parameters::Mesh::gmsh, Parameters::Manifolds::id, Parameters::Mesh::initial_refinement, Parameters::Mesh::initial_refinement_at_boundaries, refine_triangulation_at_boundaries(), Parameters::Mesh::refine_until_target_size, setup_periodic_boundary_conditions(), Parameters::Mesh::simplex, Parameters::Manifolds::size, Parameters::Mesh::target_size, and Parameters::Mesh::type.
refine_triangulation_at_boundaries()
template<int dim, int spacedim = dim> void refine_triangulation_at_boundaries (const std::vector< int > boundary_ids, const unsigned int n_refinement, parallel::DistributedTriangulationBase< dim, spacedim > & triangulation)
Refine a mesh around specific boundary ids.
Parameters
[in] n_refinement The number of times the boundary should be refined
[in] boundary_ids The boundary ids for which the cells should be refined
[in,out] triangulation The triangulation on which refinement must be carried out
Definition at line 96 of file grids.h.
setup_periodic_boundary_conditions()
template<int dim, int spacedim = dim> void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const BoundaryConditions::BoundaryConditions< spacedim > & boundary_conditions)
Modifies the triangulation to setup periodic boundary conditions in the case of CFD simulations.
Parameters
triangulation The triangulation to which a grid is attached
boundary_conditions The information about the boundary conditions id. This is used to set-up the periodicity of the domain
Definition at line 384 of file grids.cc.
References BoundaryConditions::BoundaryConditions< dim >::id, BoundaryConditions::periodic, BoundaryConditions::BoundaryConditions< dim >::periodic_direction, BoundaryConditions::BoundaryConditions< dim >::periodic_id, BoundaryConditions::BoundaryConditions< dim >::size, and BoundaryConditions::BoundaryConditions< dim >::type.